apiVersion: apps/v1
kind: Deployment
metadata:
  name: myknappdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myknappod
  template:
    metadata:
      labels:
        app: myknappod
    spec:
      containers:
        - name: myknextapp
          image: knextapp:1.0.0
          ports:
            - containerPort: 8080